name: crawl
on:
  push:
    branches: [master]
#   schedule:
#     - cron: "*/1 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo 'crawler running'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
